### PR TITLE
Added search_tweets tag, and urlize_twitter filter

### PR DESCRIPTION
**Pull request by vdboor**
Hi,

I've used your twitter-tag project with great enthusiasm in a project of mine.
I also needed some enhancements to the library, like searching for tweets instead of listing the user feed.
They are included in this pull-request. I hope you can include it in the official version, and soon release it as a new version so everyone benefits! (and I can remove a github requirement line.. ;-)

Greetings,
Diederik

### CODE REVIEW

**Comment by coagulant** [comment]
Hello, Diederik!
Thanks for your contribution, I definetly like search tag fuctionality added.
I will review the changes and let you know when I merge.

**Comment by vdboor** [comment]
Great to hear, and good to know you're checking things first :)

**Comment by vdboor** [comment]
Hi, did you have a change to look at the pull request yet? :-)

**Comment by coagulant** [comment]
Oh, sorry, been quite busy with my other projects. Will check soon.

**Comment by Gwildor** [comment]
Any news on this? I personally require the search by tag option, so would love it if this request makes it soon.

**Comment by coagulant** [comment]
I rewrote django-template-tag using modern and currently supported libraries (due to Twitter API 1.0 deprecation and possible python 3 support in future). I've added my draft implementation of `search_tweets`, and used some of your ideas. It's not finished, but still... Hope you'll like it.
https://github.com/coagulant/django-twitter-tag/commits/dev

**Comment by vdboor** [comment]
Wonderful! :) Glad to see you're working on it with this attention, and I've love to use the next release.

**Pull request closed without merging**
