### PR TITLE
Make Tweet datetime timezone aware

### PR DESCRIPTION
**Pull request by aaronkurtz**
Sets the tweet datetime's timezone to UTC, so it will play better with local times.

### CODE REVIEW

**Comment by coagulant** [comment]
What if I'm using `USE_TZ = False` in my code? I think we should handle both conditions. 
Btw, tests are not passing, partially because of that.

Btw, date parsing issue is also discussed in #24

**Comment by tzenderman** [comment]
Hey @coagulant, will you merge this in if that bug is fixed?

**Comment by coagulant** [comment]
@tzenderman I'll merge 9734f27 if tests pass. Right now I think proposed solution is incomplete.

Btw, hashtag URLification is already fixed in 372ade26.

**Comment by tzenderman** [comment]
Sounds good, I will look into this soon and send a PR for it...

**Comment by tzenderman** [comment]
Hey @coagulant, see PR #38. Let me know when you think you think it will be published to pypi. Thanks!

**Pull request closed without merging**
