### PR TITLE
Add timezone support to twitter tag.

### PR DESCRIPTION
**Pull request by tzenderman**

### CODE REVIEW

**Comment by coagulant** [comment]
Could you please remove pytz as depencency and squash commits?

**Comment by tzenderman** [comment]
I tried making it work with django.utils.tzinfo, but it wasn't working in older versions of django(1.3). Any reason you don't want to add pytz as a dependency?

Also, I haven't used tox before, but when I run `tox -v` locally, all tests are passing. It seems like in the Travis Client though there is a dependency conflict between `nose` and `httppretty`?

**Comment by coagulant** [comment]
I'd like to see USE_TZ=False support too. Making all datetimes aware instead of naive is not backwards-compatible.

**Comment by tzenderman** [comment]
Got it. I will update it very soon.

**Comment by coagulant** [comment]
> I tried making it work with django.utils.tzinfo, but it wasn't working in older versions of django(1.3).

Feel free to ignore 1.3 support.

> Any reason you don't want to add pytz as a dependency?

Django doesn't require it, so why should we?

> It seems like in the Travis Client though there is a dependency conflict between nose and httppretty

I'll look into it.

Thanks for your work!

**Comment by tzenderman** [comment]
Awesome, thanks! And glad to help out, thank you for the package!

**Comment by tzenderman** [comment]
Good to go, that should work for django 1.4 and higher. I didn't remove django 1.3 from the tox files, I'll let you do that... Let me know when it will published. Thanks!

**Comment by coagulant** [comment]
Merged in f098a6d24aadad9756a5a57e0c8023fae2d9a825
Next release in a few days

**Pull request closed without merging**
